-- The original meals entry claimed snacks/menu/allergies/nutrition, which the
-- more specific nutrition entries below cover better. Narrow it so it stays the
-- general "do you provide meals" answer and stops shadowing them.
UPDATE chatbot_faq
SET keywords = 'meal,meals,lunch,breakfast,dinner,halal,vegetarian,vegan,diet,dietary,feeding'
WHERE category = 'meals';

INSERT INTO chatbot_faq (question, answer, category, keywords) VALUES
('What food do you serve?','Fresh meals and snacks are cooked on site each day and planned with our nutritionist. Menus rotate weekly and are shared with families in advance.','nutrition','food,menu,menus,cook,cooking,kitchen,fresh,serve,serving,dishes,cuisine'),
('How do you handle allergies?','Every allergy and intolerance is recorded on your child''s file at registration and posted in the kitchen and their room. Staff are trained on avoidance and on using an adrenaline auto-injector where one is prescribed.','nutrition','allergy,allergies,allergic,intolerance,intolerant,epipen,anaphylaxis,nut,nuts,dairy,gluten,lactose'),
('Is the food organic?','We buy fresh produce locally and prioritise organic where it is available and practical. We are happy to share our suppliers and a sample menu on a tour.','nutrition','organic,natural,fresh,local,sourced,supplier,suppliers,produce,quality'),
('What snacks are provided?','Two snacks are served daily, mid-morning and mid-afternoon, alongside breakfast and lunch. Snacks are fruit, vegetables, dairy or wholegrain based, with no added sugar.','nutrition','snack,snacks,fruit,drinks,water,milk,sugar,juice,morning tea,afternoon tea'),
('What are your safety procedures?','Access to the building is controlled and logged, cameras cover entrances, corridors and play areas, and only named adults on your child''s collection list may take them home. Fire drills run monthly.','safety','safety,secure,security,camera,cameras,cctv,access,protocol,protocols,procedure,procedures,fire drill,collection,pickup'),
('What is your sick child policy?','Please keep your child at home if they have a fever, vomiting, diarrhoea or a contagious rash, and for 24 hours after symptoms stop. If a child becomes unwell with us we will call you straight away.','safety','sick,sickness,ill,illness,unwell,fever,temperature,vomiting,diarrhoea,diarrhea,contagious,infection,virus,cough'),
('What happens if my child is injured?','Minor bumps are treated by a first-aid trained member of staff and written up in an incident report you receive the same day. For anything more serious we call you immediately and, if needed, emergency services.','safety','injury,injured,hurt,accident,incident,bump,fall,first aid,bleeding,bruise'),
('Do you have emergency procedures?','Yes. We hold written evacuation, lockdown and medical emergency plans, practise them regularly, and keep every child''s emergency contacts and medical details to hand in a go-bag.','safety','emergency,evacuation,evacuate,lockdown,disaster,crisis,ambulance,drill,plan,plans'),
('What is your teaching approach?','Play-based and child-led, with adults planning around what each group is curious about. Older groups add early literacy and numeracy through games and hands-on materials rather than worksheets.','curriculum','approach,method,methodology,philosophy,pedagogy,montessori,reggio,eyfs,play based,child led,teaching style'),
('Do you help with potty training?','Yes, and we follow your lead on timing. We keep the routine identical to the one you use at home, change without fuss when there are accidents, and update you daily on how it is going.','curriculum','potty,toilet,toileting,training,nappy,nappies,diaper,diapers,pull ups,accidents'),
('How do you prepare children for school?','Our pre-school year builds the habits school expects: listening in a group, finishing work that has become difficult, managing their own belongings, and speaking up in front of others, alongside early literacy and numeracy.','curriculum','school ready,school readiness,kindergarten,kg,prepare,preparation,transition,primary,fs1,fs2,next year'),
('What does a typical day look like?','Arrival and free play from 7:00, breakfast, a circle or group session, focused activities, outdoor play, lunch, rest or quiet time, then afternoon activities until collection. Each age group has its own version.','curriculum','typical day,daily schedule,routine,timetable,agenda,day look,structure,nap,rest time'),
('What payment methods do you accept?','We accept bank transfer, credit and debit cards, and cheque. Fees are invoiced per term, and a monthly instalment plan is available on request.','payment','payment,pay,method,methods,card,cash,cheque,check,bank,transfer,instalment,installment,invoice,billing'),
('Do you offer any discounts?','Yes. We offer a sibling discount, and a reduction for paying a full year up front. Corporate rates are available for some employers. Our admissions team will confirm what applies to you.','payment','discount,discounts,sibling,siblings,offer,offers,reduction,concession,scholarship,corporate,promotion'),
('What qualifications do your staff have?','All room leaders hold a recognised early years qualification and our senior team have degrees in early childhood education. Every member of staff is first-aid trained and background checked before starting.','staff','qualification,qualifications,qualified,trained,training,teacher,teachers,staff,degree,certified,experience,background check,vetted'),
('What is your staff to child ratio?','Ratios are 1:3 for babies, 1:5 for toddlers, 1:8 at two to three, 1:10 at three to four and 1:12 for our pre-school groups. Room leaders are additional to these numbers.','staff','ratio,ratios,how many,staff to child,class size,group size,caregiver,carers,per child,supervision'),
('Can parents volunteer or visit?','Yes. Parents are welcome to read to a group, share a skill or join trips and celebrations. We ask for a background check before any unsupervised contact with children other than your own.','other','volunteer,volunteering,help,helping,parent involvement,participate,join in,committee,fundraising,visit')
ON CONFLICT DO NOTHING;
